package com.cts.fasttack.bank.client.ws.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;

/**
 * This class was generated by Apache CXF 3.2.2
 * 2018-02-16T16:32:21+02:00
 * Generated source version: 3.2.2
 *
 */
@WebService(targetNamespace = "http://sab/", name = "CardTokenPortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CardTokenPortType {

    /**
     * В случае если токенизация разрешена, в ответе возвращается номер телефона для отправки клиенту OTP кода
     */
    @WebMethod(action = "urn:confirmProvisioning")
    @Action(input = "urn:confirmProvisioning", output = "http://sab/CardTokenPort/confirmProvisioningResponse")
    @WebResult(name = "confirmProvisioningResponse", targetNamespace = "http://sab/", partName = "body")
    public ConfirmProvisioningResponse confirmProvisioning(
        @WebParam(partName = "body", name = "confirmProvisioning", targetNamespace = "http://sab/")
        ConfirmProvisioning body
    );

    /**
     * Данный запрос передается во внутреннюю систему банка для отправки значения PassCode в теле SMS.
     */
    @WebMethod(action = "urn:sendOTP")
    @Action(input = "urn:sendOTP", output = "http://sab/CardTokenPort/sendOTPResponse")
    @WebResult(name = "sendOTPResponse", targetNamespace = "http://sab/", partName = "body")
    public SendOTPResponse sendOTP(
        @WebParam(partName = "body", name = "sendOTP", targetNamespace = "http://sab/")
        SendOTP body
    );

    /**
     * internal operation to handle message processing
     */
    @WebMethod(action = "urn:mediate")
    @Action(input = "urn:mediate", output = "http://sab/CardTokenPort/mediateResponse")
    @WebResult(name = "mediateResponse", targetNamespace = "http://sab/", partName = "body")
    public java.lang.String mediate(
        @WebParam(partName = "body", name = "mediate", targetNamespace = "http://sab/")
        java.lang.String body
    );
}
