package com.cts.fasttack.common.core.dict;

public enum RecommendationReasons {
    ACCOUNT_TOO_NEW_SINCE_LAUNCH("ACCOUNT_TOO_NEW_SINCE_LAUNCH"),
    ACCOUNT_TOO_NEW("ACCOUNT_TOO_NEW"),
    ACCOUNT_CARD_TOO_NEW("ACCOUNT_CARD_TOO_NEW"),
    ACCOUNT_RECENTLY_CHANGED("ACCOUNT_RECENTLY_CHANGED"),
    SUSPICIOUS_ACTIVITY("SUSPICIOUS_ACTIVITY"),
    INACTIVE_ACCOUNT("INACTIVE_ACCOUNT"),
    HAS_SUSPENDED_TOKENS("HAS_SUSPENDED_TOKENS"),
    DEVICE_RECENTLY_LOST("DEVICE_RECENTLY_LOST"),
    TOO_MANY_RECENT_ATTEMPTS("TOO_MANY_RECENT_ATTEMPTS"),
    TOO_MANY_RECENT_TOKENS("TOO_MANY_RECENT_TOKENS"),
    TOO_MANY_DIFFERENT_CARDHOLDERS("TOO_MANY_DIFFERENT_CARDHOLDERS"),
    LOW_DEVICE_SCORE("LOW_DEVICE_SCORE"),
    LOW_ACCOUNT_SCORE("LOW_ACCOUNT_SCORE"),
    OUTSIDE_HOME_TERRITORY("OUTSIDE_HOME_TERRITORY"),
    UNABLE_TO_ASSESS("UNABLE_TO_ASSESS"),
    HIGH_RISK("HIGH_RISK"),
    LOW_PHONE_NUMBER_SCORE("LOW_PHONE_NUMBER_SCORE"),
    ;

    RecommendationReasons(String values) {
        this.values = values;
    }

    private String values;

    public String getValue() {
        return values;
    }
}
