package com.cts.fasttack.mdes.server.dict;

/**
 * @author a.lipavets
 */
public enum ActivationMethodType {
    TEXT_TO_CARDHOLDER_NUMBER,
    EMAIL_TO_CARDHOLDER_ADDRESS,
    CARDHOLDER_TO_CALL_AUTOMATED_NUMBER,
    CARDHOLDER_TO_CALL_MANNED_NUMBER,
    CARDHOLDER_TO_VISIT_WEBSITE,
    CARDHOLDER_TO_USE_MOBILE_APP,
    ISSUER_TO_CALL_CARDHOLDER_NUMBER
}
