
package com.cts.fasttack.bank.client.ws.client.cardPT;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "DataServiceFault", targetNamespace = "http://ws.wso2.org/dataservice")
public class DataServiceFault_Exception
    extends Exception
{

	private static final long serialVersionUID = -7748085494957297662L;

	/**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private DataServiceFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public DataServiceFault_Exception(String message, DataServiceFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public DataServiceFault_Exception(String message, DataServiceFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.cts.fasttack.bank.client.ws.client.cardPT.DataServiceFault
     */
    public DataServiceFault getFaultInfo() {
        return faultInfo;
    }

}
